# Sam's Tabletop Adventure Quest System
# In Emacs org-mode
#    ______________   ____   _____
#   / ___/_  __/   | / __ \ / ___/
#   \__ \ / / / /| |/ / / / \__ \ 
#  ___/ // / / ___ / /_/ / ___/ / 
# /____//_/ /_/  |_\___\_\/____/ [0.1a]
# "Pronouned STACKS"
# ssaammp at gmail 2014-12-15

* META
** Why I made STAQS
I grew up playing a game called "Quest", where one person tells his friend that "you're in the woods, and you need to become US president", or something like that. It was fun and irreverant. Then, I started playing Dungeons and Dragons, and I missed that improvizational, insane element. I made STAQS because I wanted to make something like DND, but without the pre-written aspects.
** What do I need for STAQS?
You need a place to play, some RNG [d20, d6, coins, or OTHER], pencils, paper, people and time.
** Changelog
[0.0.4b] Removed megaSTAQS/miniSTAQS distinction, major rewrites/reorganization
[0.0.3a] Created megaSTAQS
[0.0.2a] STAQS has been lightly playtested. What was once called "Orthodox staqs" is now "ministaqs". Various rule tweaks, commentary additions, etc.
[0.0.1a] STAQS HAS NOT been playtested. This is a testing release of STAQS, designed to help make STAQS the best it can be. The rules are not set in stone yet. If you have v0.0.1a, let me know any changes you make, or what changes you think I should make. ssaammp@gmail.com
*

* ESSENTIALS
** Elements of Characters
*** What kind of characters to create?
	Nothing is predifined in staqs. Players should create a character they want to play as. These characters can be based on anything from an abstract collection of related ideas to a character from a video game. Characters benefit from elaboration. Just "Wizard" is boring, but "Middle-aged perverted wizard" has infinite possibilities.
	Adding humor and in-jokes to characters is the bread and butter of traditional staqs, though staqs is fully capable of a serious campaign.
*** Class
	Class is indicitave of who or what a player IS. Stats, abilities, and items should be based on class.
	Class can be upgraded or re-trained as part of a major reward, or maybe if the game just needs a mix up. In a class upgrade, fundamental abilities are typically traded up from more basic/physical to more advanced/magical ones. In a class re-training, abilities are typically modified to ones that better fit the party, or provide more interesting gameplay.
*** Name/Gender/Height/Weight/Age/Portrait/Description
The player should create these. The GM should pay attention to them when building the world. Creating a black-hole character with 40 times the mass of the sun is not advised.
*** Stats and Values
	Traditionally, all characters have the same set of stats, with corresponding values. Stats should not be utility like STRENGTH, especially if the player character is obviously one with lower or higher strength based on other attributes. Stats should be more specific.
	For example, if the party is in a town populated by skeletons, a GUTS stat for not being spooked by skeletons should probably be arranged. Ideally, players will not be aware of the function of the stat before it becomes useful.
	When new stats are introduced, the GM should introduce stats in pairs or threes and allow players to allocate a fixed total of points across them. If not, the GM should offer equal trades in exchange for stat bonuses. For example, a pious player could sacrifice their money for more FAITH.
	Rolling for stats is considered dirty, because an unlucky player can have a long-term disadvantage.
*** HP
	Less HP = More dead. If a player is going to be highly evasive, give them low HP. If they're "tanky", give them higher HP.
*** Status
	Status is like stats, but temporary. In a more serious staqs environment, keeping status in an easily erasable medium such as a whiteboard, phone, or computer is advisable.
	Character-specific stats along the lines of "MP" are highly useful for limiting magic abilites, as they are usually more versetile and powerful than physical staqs abilities.
	Harmful/helpful/neutral status effects are an effective way to keep track of various things. If the players are in a toxic gas maze, a TOXIC status can keep players more confident about how poisoned they are.
*** Abilities
** Difficult Actions
   One of the core elements of STAQS is the "difficult actions", or DA system. Depending on how hard an action is, you have a chance to complete the action (success), fail the action (failure), or do the closest opposite of the action (critfail). Critfails don't have to be negative, but they should violate the intent of the action.
*** Action difficulty ratings
This is up to the GM, but it's best for the players if you let them know how you're breaking things down. Difficulty falls into different numbered "classes", and depending on the campaign, you'll want to address them by either name or number.
 1. Hard actions: Difficult actions you know the player is capable of.
 2. Harder actions: Actions for which you're unsure of the player's ability.
 3. Unlikely actions: Actions that are especially difficult, or unsuited for the particular player.
 4. Improbable actions: Actions which the player is not supposed to be able to do.
 5. Impossible actions: Actions which nobody is supposed to be able to do.
*** Probability numbers
**** d20 system
|-------+--------------+-------------|
| CLASS | SUCCESS      | CRITFAIL    |
|-------+--------------+-------------|
|     1 | >=10         | NONE        |
|     2 | >=15         | 1 then <=2  |
|     3 | 20           | 1 then <=10 |
|     4 | 20 then >=10 | 1           |
|     5 | 20 then >=19 | >= 5        |
|-------+--------------+-------------|
**** d6 system
Roll one at a time for extra hype
|-------+----------+----------|
| CLASS | SUCCESS  | CRITFAIL |
|-------+----------+----------|
|     1 | 1d6 >=2  | NONE     |
|     2 | 2d6 >=8  | 3d6 3    |
|     3 | 3d6 >=16 | 3d6 4    |
|     4 | 3d6 >=17 | 3d6 5    |
|     5 | 3d6 18   | >=5      |
|-------+----------+----------|
**** coin flips
Call heads or tails before flipping. Or before each flip if you're feeling lucky. Every flip counts, so flipping called then uncalled will always result in a 2-flip failure without critfail.
|-------+-----------+-------------|
| CLASS | SUCCESS   | CRITFAIL    |
|-------+-----------+-------------|
|     1 | Called    | NONE        |
|     2 | 2x Called | 7x uncalled |
|     3 | 4x Called | 5x uncalled |
|     4 | 5x Called | 4x uncalled |
|     5 | 7x Called | 2x uncalled |
|-------+-----------+-------------|
**** Other RNG
If you're a rebel, you can use other probability systems. Try to align it roughly to these numbers:
 1. Success is a less than 100% chance. No critfail.
 2. Success <= 1/3. Critfail 1/200.
 3. Success <= 1/15. Critfail 1/50.
 4. Success <= 1/50. Critfail is 1/15.
 5. Success <= 1/200. Critfail is 1/3.
** Timeline system
