# Sam's Tabletop Adventure Quest System
# In Emacs org-mode
#    ______________   ____   _____
#   / ___/_  __/   | / __ \ / ___/
#   \__ \ / / / /| |/ / / / \__ \ 
#  ___/ // / / ___ / /_/ / ___/ / 
# /____//_/ /_/  |_\___\_\/____/ [0.0.3a]
# "Pronouned STACKS"
# ssaammp at gmail 2014-09-07

STAQS is licensed under the OPEN GAME LICENSE 1.0a
A copy of OGL is in 'LICENSE'

* Intro To STAQS
** Why I made STAQS
I grew up playing a game called "Quest", where one person tells his friend that "you're in the woods, and you need to become US president", or something like that. It was fun and irreverant. Then, I started playing DND, and I missed that improvisational, creative aspect of Quest. I realized the issue was that a bunch of people already decided what everything is, and how everything works, and it's all printed in books that you pay for when you want to play DND. Isn't that lame? So, I made STAQS because I wanted something where me and my friends could all sit down at a table as if we're playing DND, but do something kind of like Quest.
** WHAT IS STAQS?
STAQS is a game that's played on a table, designed for fun and freedom.
** What do I need for STAQS?
STAQS is designed so that it can easily by played on lined paper. You might want dice. You can also just flip coins, pull cards out of a deck, bet on sports, flip buttered toast, pull a wishbone, use a magic 8-ball, use random.org, draw straws, use a spinner, or anything else.

I also made some optional character sheets, which should be in the folder with this document.
** Version notes
*** Changelog
[0.0.3a] Created megaSTAQS
[0.0.2a] STAQS has been lightly playtested. What was once called "Orthodox staqs" is now "ministaqs". Various rule tweaks, commentary additions, etc.
[0.0.1a] STAQS HAS NOT been playtested. This is a testing release of STAQS, designed to help make STAQS the best it can be. The rules are not set in stone yet. If you have v0.0.1a, let me know any changes you make, or what changes you think I should make. ssaammp@gmail.com

* miniSTAQS Guidebook - READ before other staqs
** Intro
This is a catalogue of original staqs rules, which define ministaqs. If you follow all of these rules directly, you'll be playing ministaqs. Ministaqs contains intentional insanity and loopholes which are designed to increase the chaotic and improvizational aspects of the game. Even if you don't follow the original rules, make sure to read this.
** Roles
 1. The GM creates the game universe, and controls everything within the rules, including the rules themselves.
 2. Players create and play a single character in the game universe.
** HP
In ministaqs, every player has a "current HP", denoted on their character sheet, as well as a "max HP". HP is how dead or not dead the player is. Higher values are less dead, lower values are more dead.
*** Overheal
If you want to give a player more health than "max health", you can give them a buffer in status which takes damage instead of the player.
*** Death
The GM decides what HP case determines death, and if a specific HP case indicates unconsciousness. HP should be used as a potential cause of death, but not as the primary cause of death.
** Player actions
*** No Question rule
If a player chooses to do something, and nobody questions it, the action is simply performed. This is called an "easy action". Even if this action would be difficult, no question means no difficulty.
*** Difficult actions
Based on player traits and difficulty of difficult actions, the GM can decide what numbers are required to complete the action.  Upon success, the player completes the action.  Upon failure;, the player does not complete the action. Upon critfail, the player completes the opposite of the action.

If you're running d20-based STAQS, this is an example of a table you'd use.
|--------------+---------+----------|
| Difficulty   | Success | Critfail |
|--------------+---------+----------|
| Difficult    |   10-20 |      n/a |
| Unlikely     |   15-20 |        1 |
| Unreasonable |   17-20 |      1-3 |
| Unthinkable  |      20 |      1-5 |
|--------------+---------+----------|

If you're running binary STAQS (coin flip based, for example):
|--------------+---------+----------|
| Difficulty   | Success | Critfail |
|--------------+---------+----------|
| Difficult    | 1xhead  | 2xtail   |
| Unlikely     | 2xhead  | 2xtail   |
| Unreasonable | 3xhead  | 2xtail   |
| Unthinkable  | 4xhead  | 2xtail   |
|--------------+---------+----------|

# RATIONALE: Traditional STAQS campaigns are meant to be chaotic, and less serious, so players are supposed to be able to do unrealistic things...with enough luck.
*** Action Denial
The GM should deny actions for only one the following reasons:
  1. Not a player action
     - The player describes a goal like "kill the boss" rather than an action.
     - The action in question is not on the part of the player.
  2. Not specific enough
     - The player describes multiple actions
     - The action is ambiguous in some way
# RATIONALE: GM's like to be controlling, but simply saying "NO" is harmful to improvisation and creativity. Players should be able to at least attempt the impossible.
** Timeline System
In time-sensitive situations, the GM will keep track of things happenning using a timeline-based system.
*** Notation
Typically, every row of a piece of lined paper will represent a time window such as 2 seconds. Every column represents a player. For example, a 6 second action fills up 3 rows of a player's timeline column.
*** Realtime vs Ingame time
Staqs with a timeline is either done in "free time" or "timestretch X". In "free time", players can take as long as they want in realtime to do ingame actions. In "timestretch X", every second of ingame time counts for X seconds of realtime. Using a very short timestretch, consider turning the situation into a form of board game or LARP.
*** Parallelizing
Since not everyone can talk at once, actions described by multiple players can be rolled into a shorter time period. This can be done either through a "turns" system, or simply by players specifying that they do something "at the same time" as each other.
*** Slow time
When time is important, but not short amounts of time, the game enters "Slow time". The GM can choose to keep track of this time in a similar way.
** Tabletop battle system
In situations where player position matters, players have the option to keep track of their position on any form of representative 2d system.
*** Notation
Any grid-based or non-grid 2 dimensional system will work.
*** 
** Being a good staqs GM
*** Keep hidden numbers/info
If you're going to keep a consistent universe, you want to keep at least a few things in number form. Write down info about each player, and let each player "feel" out their abilities from that info. If you're not going to let players know which numbers are where, you're going to have to communicate what is actually going on as best as you can.
*** Questions and assumptions
If a player clearly has intentions, based on their character traits, think about the actions they would take. Try to make it feel natural and automatic. If you aren't sure what a player would do, or what they're doing is a critical decision, ask them questions.
*** Setting goals
Depending on the players you're dealing with, goals may simply rise naturally. If you feel like players need a goal, create something that you know they will care about and work toward.
*** Rewarding players
A good GM knows how to reward players. Rewards are simple, but they vary from person to person. The best rewards are unexpected and personal. Players should be rewarded for playing the game creatively, being ambitious, working toward goals, 
** Traditions
*** Seating
 - The staqs GM is encouraged to sit at the side, rather than at the end of the table, as to be physically closer to the players
 - 
*** Communications
 - Players are encouraged to communicate

* megaSTAQS
#     __  __________________ S
#    /  |/  / ____/ ____/   |T
#   / /|_/ / __/ / / __/ /| |A
#  / /  / / /___/ /_/ / ___ |Q
# /_/  /_/_____/\____/_/  |_|S
** Intro
megaSTAQS is a major extension of miniSTAQS with way more guidelines to shake things up, and way more potential to tie into other elements of tabletop gaming.
You can think of megaSTAQS as a comprehensive set of house rules that tie into each other...mostly. megaSTAQS contains the rules for ministaqs, but adjusts (violates?) many of them.
** Roles
 1. The GM(s) create at least one game universe, 
 2.
